export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const SET_VALUE = 'SET_VALUE';
export const SET_SPECIFIC_COUNTRY = 'SET_SPECIFIC_COUNTRY';
export const SET_COUNTRY_HOLIDAYS = 'SET_COUNTRY_HOLIDAYS';
export const SET_PUBLIC_HOLIDAYS = 'SET_PUBLIC_HOLIDAYS';